# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dependencies' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dependencies
  pod "Moya", '~> 14.0'
  pod "RxSwift", '~> 5.0'
  pod "Starscream", '>= 4.0.0'
  pod "Eureka", '~> 5.2'
  pod "Yams"
  pod "PromiseKit", '~> 6.8'
  pod "ReSwift"
  pod "ReachabilitySwift"
  pod "RNCryptor", '~> 5.0'

end
